### ISSUE TITLE
Pylyzer install in a virtual environment return error on vscode starting

### ISSUE THREAD

**Issue by danny-huang-openfind** [mtshiba/pylyzer#104]
So I am using pylyzer extension in vscode, and before that I have already install pylyzer in a virtual environment since I am using poetry, but these error pop-up, I consider that is a no for me to install pylyzer in venv instead of host.

![image](https://github.com/user-attachments/assets/ff2ad655-2e90-4e1b-acaf-c07d63d590c3)

I just want to ask some question:
1. First of all, did I do something wrong? maybe it should be work?
2. Is it recommend to do this (install pylyzer in virtual environment)? If no, why (since I can do the exact same thing while using ruff)?
3. I want to know if this kind of adjustment is in planning, also.

**Comment by mtshiba** [comment]
1. The VSCode extension v0.0.10 looks up the workspace's `.venv/bin` directory, so it should work now.
Support for virtual environments located in other directories will be implemented in the future.
2. Since pylyzer is a standalone binary application, there is little advantage in installing it in a virtual environment. I recommend installing it globally unless you have a specific preference.
