### ISSUE TITLE
LSP completions don't work for sub-modules

### ISSUE THREAD

**Issue by rishikanthc** [mtshiba/pylyzer#108]
The sub-modules completion doesn't work.
For eg. If i type `import os` there's a completion for it and works fine. Next however, if I try to access `os.path`, no completions show up for `path` or any of its related members. This is the behavior for all packages I use.

### My Setup
Mac OS running M3 Max
helix editor configured as per [this](https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#python---ruff--pyright--pylyzer)

Any help would be appreciated. Does pylyzer not fully support the helix text editor ?

**Comment by mtshiba** [comment]
This is an essential difficulty with completion.
Suppose we type `os` when the os module has not been imported and then import it using completion.
If we then type `os.path.` quickly, completion may not work correctly because the inserted module has not been checked and the `os.path` identifier has not yet been resolved.
In fact, if we type `os.path.` after the os module has already been imported, members should be listed correctly.

The incremental check has been improved in the latest version (v0.0.66), which has alleviated the problem, but the problem will remain essentially the same if your typing speed is fast enough.
