### ISSUE TITLE
pip install pylyzer to install erg as well

### ISSUE THREAD

**Issue by h5rdly** [mtshiba/pylyzer#50]
Hi,

First of all, cheers for this awesome package.

Would it be possible to add the Erg installation to setup.py, or by some other method, so that erg is installed when one runs
`pip install pylyzer`?

(ie the same way `pandas` installs `numpy` etc. for you when you run `pip install pandas`)

Thanks,
Eli

**Comment by mtshiba** [comment]
The reason erg is in pylyzer's dependencies is not because pylyzer calls the Erg compiler. What is really needed is a set of type definition files for the Erg standard library. pylyzer itself can be installed with pip, but the installation of this library requires `cargo` or [ergup](https://github.com/mtshiba/ergup).

So we want to run ergup during pip installation. This is what I am currently trying to do, however, I don't know how to make the pre-install script run while installing the wheel package.

**Comment by mtshiba** [comment]
Now you can now install pylyzer using pip without any additional action.
